embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  batch_size: 32
  device: "auto"  # cpu/cuda/auto

llm:
  model: "deepseek-chat"
  temperature: 0.3
  max_tokens: 2048

retrieval:
  top_k: 3
  similarity_threshold: 0.75